### ISSUE TITLE
critical severity vulnerabilities

### ISSUE THREAD

**Issue by Axl-Lvy** [pubnub/js-chat#146]
It seem that the 2.0.0 release has critical severity vulnerabilities. After investigation, I found that this was the case for pubnub 7.2. Is it possible to change the dependency to pubnub 7.4.1 (the latest) ? Otherwise I am no longer able to use pubnub in production...

**Comment by piotr-suwala** [comment]
Hello @Axl-Lvy!

I think you can manually override the pubnub dependency on your own using either "overrides" or "resolutions" -> https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions

We will publish a new version on @pubnub/chat (0.3.0) either this or next week and we can take a look at upgrading pubnub's version so for now I believe you're good with overriding on your own until we publish a new version.

Thanks for contacting us!

**Comment by piotr-suwala** [comment]
@Axl-Lvy We updated pubnub to 7.4.2 in yesterday's release. If you find the problem persists, please create a new issue.
